set number                    " Line numbers
set nocompatible              " be iMproved, required
set mouse=a
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'bling/vim-airline'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-notes'
Plugin 'scrooloose/nerdtree'
Plugin 'klen/python-mode'
Plugin 'ervandew/supertab'
Plugin 'moll/vim-node'
" Avoid a name conflict with L9

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

colorscheme default                         " use my terminal config
set colorcolumn=+1                          "this adds a column at 80 char mark (for python and things)
set encoding=utf-8
syntax on
let g:airline#extensions#tabline#enabled = 0 " This enables some airline functionality
set laststatus=2                            "  Always enables status line
let g:airline_powerline_fonts = 1           " UTF-8 font
set wildmenu                                " emables wilemenu 
set cursorline                              " highlights the current line
set noswapfile                              " this disables the backup files and the warnings you get
set noshowmode                              " hides the mode status
set showcmd                                 " shows the command in the bottom right
set tabstop=4                               " these 2 lines make the TAB key enter 4 spaces instead
set expandtab                               " 
set softtabstop=4                           " lets you delete the 4space tabs as one character>
set shiftwidth=4                            " lets >> and << work wiht 4 space tab
set clipboard=unnamed                       " makes the clipboard a little more intuitive
map <F2> :NERDTreeToggle<CR>                " binds f2 to the nertdree plugin

autocmd CursorMovedI * if pumvisible() == 0|pclose|endif "these commands close the popup menu when entering and leaving insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" change some of the colors that don't look to great in my terminal 
hi TabLineFill ctermfg=darkgrey ctermbg=none
hi TabLine ctermfg=Blue ctermbg=DarkGrey
hi TabLineSel ctermfg=DarkGrey ctermbg=Blue
hi WildMenu ctermfg=White ctermbg=DarkBlue
hi StatusLine ctermbg=DarkGrey
hi Visual ctermbg=grey 
